use_modular_headers!

source 'https://gitee.com/zhi_lei/Spec.git'
source 'https://github.com/CocoaPods/Specs.git'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
